/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interactionValidateurB.h"


void
interaction_validateur_b_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *interaction_null_1_arg;
	void  *result_2;
	Ballon  donner_ballon_1_arg;
	int  *result_3; 
	Ballon  check_ballon_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INTERACTION_VALIDATEUR_B, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = interaction_null_1((void*)&interaction_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = donner_ballon_1(&donner_ballon_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	Ballon b; 
	strcpy(b.id, "idBall18");
	b.heure=10;
	b.minute=46;
	result_3 = check_ballon_1(&b, clnt);
	printf("Resultat : %d \n", *result_3);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	printf("Trying to connect ... \n");
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	interaction_validateur_b_1 (host);
exit (0);
}
